apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: metrics
  namespace: monitoring
provisioner: docker.io/hostpath
allowVolumeExpansion: true
---
apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: prometheus-data
  namespace: monitoring
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: metrics
  hostPath:
    path: "/Users/kbrockhoff/Volumes/prometheus-data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prometheus-claim
  namespace: monitoring
  annotations:
    volume.beta.kubernetes.io/storage-class: "metrics"
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
