apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  namespace: monitoring
spec:
  selector: 
    app: prometheus-server
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9090 
