apiVersion: apps/v1
kind: Deployment
metadata:
  name: ptip-aggregate-deployment
  labels:
    app: ptip-aggregate-svc
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path: /actuator/prometheus
      prometheus.io/port: '8082'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ptip-aggregate-svc
  template:
    metadata:
      labels:
        app: ptip-aggregate-svc
    spec:
      containers:
        - name: aggregate-svc
          image: kbrockhoff/ptip-aggregate-svc:latest
          ports:
            - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: aggregate-svc
  labels:
    app: ptip-aggregate-svc
spec:
  selector:
    app: ptip-aggregate-svc
  type: NodePort
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
