logging:
  level:
    org.springframework.integration.support.MessageBuilder: WARN
    org.springframework.boot: INFO
    org.codekaizen.demos: INFO

spring:
  application:
    name: PTIP Aggregation Service
  
server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  prometheus.metrics.export.enabled: true

cloud:
  aws:
    region:
      static: us-west-2
    stack:
      auto: false

codekaizen:
  feeds:
    baseurl: 'https://ptit-demo.kevinbrockhoff.me/feeds'
